amcl:
  ros__parameters:
    use_sim_time: True
    # AMCL이 켜져서 꼬이는 것을 방지하기 위해 타임아웃을 넉넉히 줍니다.
    bond_timeout: 40.0

bt_navigator:
  ros__parameters:
    use_sim_time: True
    bond_timeout: 40.0        # 20초로 대폭 상향 (도커 환경 대응)
    bt_loop_duration: 150     # 부하를 더 줄임
    default_server_timeout: 2 # 2.0이 아니라 반드시 '2'라고 적어야 합니다!
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    use_sim_time: True
    bond_timeout: 40.0
    topic_name: /cmd_vel
    transform_tolerance: 5.0
    controller_frequency: 5.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.01
      yaw_goal_tolerance: 0.05
      free_goal_velocity: False

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.1
      lookahead_dist: 0.06
      min_lookahead_dist: 0.03
      max_lookahead_dist: 0.15
      use_velocity_scaled_lookahead_dist: True
      robot_radius: 0.12
      inflation_cost_scaling_factor: 3.0

planner_server:
  ros__parameters:
    use_sim_time: True
    bond_timeout: 40.0
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.01
      use_astar: True

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      bond_timeout: 40.0
      transform_tolerance: 5.0
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.01
      robot_radius: 0.12
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        # inscribed radius(0.12)보다 크게 설정하여 에러 방지
        inflation_radius: 0.15 

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      bond_timeout: 40.0
      transform_tolerance: 5.0
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.12
      resolution: 0.002
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.2

map_server:
  ros__parameters:
    use_sim_time: True
    bond_timeout: 40.0
    yaml_filename: "/home/hhh/colcon_ws/src/lcode_localizer/params/lcode_map.yaml"
    topic_name: "map"
    frame_id: "map"


behavior_server:
  ros__parameters:
    use_sim_time: True
    bond_timeout: 40.0
    cycle_frequency: 5.0
    recovery_plugins: ["spin", "backup", "wait", "drive_on_heading"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names: ["controller_server", "smoother_server", "planner_server", "behavior_server", "bt_navigator", "waypoint_follower", "velocity_smoother"]
    bond_timeout: 40.0